#!/usr/bin/env bash

swaymsg "workspace 1; exec alacritty"
swaymsg "workspace 2; exec firefox"
swaymsg "workspace 4; exec slack"
swaymsg "workspace 8; exec keybase-gui"
swaymsg "workspace 9; exec thunderbird"
swaymsg "workspace 2"
